### ISSUE TITLE
Improve the output of CSS modules

### ISSUE THREAD

**Issue by umaar** [dojo/cli-create-theme#10]
The CSS module file which is output for some widgets can look like this:

![image](https://user-images.githubusercontent.com/381495/34524306-0050de0e-f093-11e7-9431-440e30b1ff78.png)

That's the calendar. It's a little overwhelming and hard to visually locate selectors in such a long list, we could improve this output by alphabetizing the selectors.

**Comment by tomdye** [comment]
I would suggest keeping `root` at the top at the very least. I'm not sure how valid this issue is as most users will search the outputted file for the classnames they are looking for.

**Comment by umaar** [comment]
That's fair, shall we close this one?

**Comment by umaar** [comment]
Actually thinking about it: I wouldn't say they will 'search' for it in all cases, since for some users, they will not know off the top of their head what the selectors are that they are looking for. But rather they will visually scan the selectors and try to make sense of which selector does what. Having some logical ordering for that can make the list easier to scan through.

Not a big deal for me, but it's something that I felt when looking through the list.

**Comment by tomdye** [comment]
Worth leaving open for discussion from the rest of the team
