### ISSUE TITLE
Create a cli-util repo which common CLI utilities

### ISSUE THREAD

**Issue by umaar** [dojo/cli-create-theme#2]
This comment explains all! https://github.com/dojo/cli-create-theme/pull/1#discussion_r155050351

**Comment by matt-gadd** [comment]
@umaar thats what the command helper in cli is for. its injected so we don't even need another repo.

**Comment by umaar** [comment]
Wow you are quick! So I think it's this thing: https://github.com/dojo/cli/blob/master/src/CommandHelper.ts ! 

Will close the issue thank you!

**Comment by tomdye** [comment]
My apologies, i forgot about the command helper, it belongs in cli-create-app

**Comment by kitsonk** [comment]
Re-opening because we have a PR that is unmerged related to this issue.

**Comment by umaar** [comment]
Shall we close this because now it has been merged?
