### ISSUE TITLE
Improve the formatting for the generated theme file

### ISSUE THREAD

**Issue by umaar** [dojo/cli-create-theme#7]
Here is what it looks like:

![image](https://user-images.githubusercontent.com/381495/34523984-b5732bf4-f091-11e7-9d69-c446ff71f6b8.png)

Should fix the extra new lines, trailing spaces and trailing comma on the last exported key-value pair.

When there are multiple widgets, the formatting can also be improved:

![image](https://user-images.githubusercontent.com/381495/34524052-f36f7656-f091-11e7-9ae3-8097a40d6aa9.png)

**Comment by agubler** [comment]
This has been fixed.
